// Package issue_375 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version (devel) DO NOT EDIT.
package issue_375

// Defines values for NotWorkingAnythingTesting.
const (
	NotWorkingAnythingTestingTest1 NotWorkingAnythingTesting = "test1"

	NotWorkingAnythingTestingTest2 NotWorkingAnythingTesting = "test2"
)

// This is not working.
type NotWorking struct {
	Anything []struct {
		Testing NotWorkingAnythingTesting `json:"testing"`
	} `json:"anything"`
}

// NotWorkingAnythingTesting defines model for NotWorking.Anything.Testing.
type NotWorkingAnythingTesting string

// NotWorkingAnythingTesting defines model for NotWorking.Anything.Testing.
type NotWorkingAnythingTesting string
